### ISSUE TITLE
Add Years for 2023 Publications and add missing DOI

### ISSUE THREAD

**Issue by MadMax93** [datasharingframework/datasharingframework.github.io#26]
- https://dsf.dev/intro/publications.html#publications
- Missing DOI for Interoperability Is a Process- The Data Sharing Framework. 
- @hhund and @schwzr should we publish the conference talks and tutorial on GMDS 2023 and MIE 2023? And in general should we add an area participation in conferences or other symposia etc.?

**Comment by hhund** [comment]
MedInfo paper doi added via 65ab465
