### ISSUE TITLE
Install DSF 1.5.1 is missing links to the project configuration (i.e. docker-compose.yml)

### ISSUE THREAD

**Issue by haemka** [datasharingframework/datasharingframework.github.io#57]
The installation guide for 1.5.1 (docs/src/v1.5.1/maintain/install.md) is missing any link to the project itself. Therefore it just describes what to change in the configuration but does not link to the basic configuration to use as baseline.

**Comment by schwzr** [comment]
From what I can see, the documentation links to the corresponding docker-compose.yml files contained in the tar.gz files.

https://dsf.dev/stable/maintain/install.html#dsf-fhir-server

under 2. and

https://dsf.dev/stable/maintain/install.html#dsf-bpe-server

under 2. contain the current “ default configurations”, including all files, which can then be adapted according to the instructions.

**Comment by haemka** [comment]
Ah, then nevermind. I was looking for actual links and therefore didn't find the links within the code blocks while skimming the page.
